### PR TITLE
Updating Process Spec and Process Run attribute tables

### PR DESCRIPTION
**Pull request by xperrylinn**
Removed ingredients and output_material rows as they are currently not attributes that belong to ProcessSpec and ProcessRun objects.

### CODE REVIEW

**Comment by kroenlein** [comment]
The attributes exist, they are just not driven by this object.  Would it make more sense to keep the attribute and change `Required` to `Implicitly defined`?  This is also relevant to the `measurements` attribute on Measurement Runs.

**Comment by xperrylinn** [comment]
> The attributes exist, they are just not driven by this object. Would it make more sense to keep the attribute and change `Required` to `Implicitly defined`? This is also relevant to the `measurements` attribute on Measurement Runs.

That could work. I would also suggest `Defined in Ingredient Spec` or `Defined in Material Spec` as an explicit explanation of where those data live. 

I was also thinking it could be also useful in the paragraph above the table to spell out the connectivity of Process Specs with Ingredient Specs and Material Specs. For example, "A Process Spec is connected to an Ingredient Spec object, through a Process Spec field in Ingredient Spec objects ..." or something like that. I guess a more general question that I have is the connections between GEMD objects from directed acyclic graphs. How much are we trying to spell that out in the docs or is the goal to keep it lean?

**Review by kroenlein — APPROVED** [review]
@xperrylinn I think this makes sense.  Thoughts?

@maxhutch I marked fields with values that are set automatically in gemd-python as `Implicit` rather than `Required`

**Comment by xperrylinn** [comment]
> @xperrylinn I think this makes sense. Thoughts?
> 
> @maxhutch I marked fields with values that are set automatically in gemd-python as `Implicit` rather than `Required`

**Comment by xperrylinn** [comment]
> > @xperrylinn I think this makes sense. Thoughts?

@kroenlein - LGTM! Thank you for making those edits. 

(P.S. ignore the closing/opening of this PR, I accidentally clicked `Close with comment` button 😂 )

**Pull request merged**
