### PR TITLE
Small suggestion to definition of Process Object

### PR DESCRIPTION
**Pull request by xperrylinn**
Suggesting the following change:

Process Object: Describes an operation used with the goal of transforming a material.

to 

Process Object: Describes an operation used with the goal of transforming one or more materials into a new material.

### CODE REVIEW

**Comment by maxhutch** [comment]
Thanks for the suggestion @xperrylinn !  I'm reassigning the review to @kroenlein , who is the owner of these docs now.

**Review by kroenlein — COMMENTED** [review]
I see where you are going, but does that sentence still match the idea of annealing a steel rod or desiccating a powder?

**Comment by xperrylinn** [comment]
> I see where you are going, but does that sentence still match the idea of annealing a steel rod or desiccating a powder?

I think I see the point you are making with the examples you gave. Is your concern about the "new" adjective? Where you might not necessarily be creating new material, but purifying it as is in the example of removing water from a powder with a desiccant.

I would say yes. My reasoning is that any changes to the chemical structure as in annealing or changes to composition as with removing water from a solid would constitute a new material.

**Comment by kroenlein** [comment]
> > I see where you are going, but does that sentence still match the idea of annealing a steel rod or desiccating a powder?
> 
> I think I see the point you are making with the examples you gave. Is your concern about the "new" adjective? Where you might not necessarily be creating new material, but purifying it as is in the example of removing water from a powder with a desiccant.
> 
> I would say yes. My reasoning is that any changes to the chemical structure as in annealing or changes to composition as with removing water from a solid would constitute a new material. Curious to hear your thoughts as I'm still building up the intuition in working with the new data model.

The `new` was the bit sticking in my craw, but for clarity it is an improvement over what's there.  I've thought about `possibly new` or `novel` but that doesn't make it better.  How do you feel about `Describes an operation that generates an output material from one or more material inputs.`?

**Comment by xperrylinn** [comment]
> > > I see where you are going, but does that sentence still match the idea of annealing a steel rod or desiccating a powder?
> > 
> > 
> > I think I see the point you are making with the examples you gave. Is your concern about the "new" adjective? Where you might not necessarily be creating new material, but purifying it as is in the example of removing water from a powder with a desiccant.
> > I would say yes. My reasoning is that any changes to the chemical structure as in annealing or changes to composition as with removing water from a solid would constitute a new material. Curious to hear your thoughts as I'm still building up the intuition in working with the new data model.
> 
> The `new` was the bit sticking in my craw, but for clarity it is an improvement over what's there. I've thought about `possibly new` or `novel` but that doesn't make it better. How do you feel about `Describes an operation that generates an output material from one or more material inputs.`?

`Describes an operation that generates an output material from one or more material inputs.` sounds perfect to me!

**Review by kroenlein — APPROVED** [review]

**Pull request merged**
